version: 0.2
envi:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /myapp/docker-registry/username
    DOCKER_REGISTRY_PASSWORD: /myapp/docker-registry/password
    DOCKER_REGISTRY_URL: /myapp/docker-registry/url

phases:

  pre_build:
    commands:
      - echo "Logging in to Docker Hub..."
      - echo $DOCKER_REGISTRY_PASSWORD: | docker login -u $/myapp/docker-registry/username --password-stdin

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t cicd-project .

      - echo "Tagging Docker image..."
      - docker tag cicd-project iamprathap/cicd-project:latest

  post_build:
    commands:
      - echo "Pushing Docker image to Docker Hub..."
      - docker push iamprathap/cicd-project:latest

artifacts:
  files:
    - appspec.yml
    - scripts/**/*
